name: dandd_sales_app
description: Enterprise-level Sales and Distribution application for Traders and Manufacturing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Routing
  go_router: ^16.2.4
  
  # API Management
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Authentication & Storage
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.2
  
  # Logging
  logger: ^2.0.2+1
  
  # Utilities
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  uuid: ^4.2.2
  
  # OTP
  pinput: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.3
  retrofit_generator: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
